name: Build premconverter

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: make test
      - run: make
      - name: Bundle output
        run: cd bin && zip ../premconverter-$(( GITHUB_RUN_NUMBER )).zip premconverter*
      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          name: premconverter
          path: premconverter-${{ github.GITHUB_RUN_NUMBER }}.zip